resource_registry:
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/computesriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ControllerSriov::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  NeutronTunnelTypes: 'geneve'
  NeutronNetworkType: ['geneve', 'vlan']
  NeutronEnableDVR: false
  NeutronPluginExtensions: "port_security,qos,segments,trunk,placement"
  NeutronSriovAgentExtensions: "qos"
  #NeutronTunnelTypes: 'vxlan'
  #NeutronNetworkType: ['vxlan', 'vlan']

  ComputeSriovCount: 2
  NeutronNetworkVLANRanges: dpdk1:514:514,dpdk2:516:516

  NeutronBridgeMappings: 'datacentre:br-ex,sriov1:br-link1,sriov2:br-link2'
  NeutronFlatNetworks: 'datacentre,dpdk1,dpdk2,sriov1,sriov2'
  NeutronPhysicalDevMappings: ["sriov1:eno3", "sriov2:eno4"]
  NovaPCIPassthrough:
  - devname: "eno3"
    trusted: "true"
    physical_network: "sriov1"
  - devname: "eno4"
    trusted: "true"
    physical_network: "sriov2"

